- components/footer.js
- components/layout.js
- pages/countries.js
- pages/index.js
A static footer with links. Based on the UI mockup.
> Implement Footer component

- components/measurement/CommonDetails.js
- components/measurement/MeasurementContainer.js
- components/measurement/StatusHeader.js
- components/measurement/nettests/default.js
- components/measurement/nettests/ndt.js
- components/measurement/nettests/web_connectivity.js
- components/measurement/nettests/whatsapp.js
- pages/measurement.js
These are mostly copy improvements and some bug fixes.
I also implement what is specified in: https://github.com/ooni/explorer/issues/38
> Improvements to measurement pages

- components/Layout.js
- components/date-picker.js
- components/footer.js
- components/search/filter-sidebar.js
- components/search/filter-tabs.js
- components/search/results-list.js
- pages/search.js
> Various fixes to Search Page

- .travis.yml
- package.json
- yarn.lock
This fixes issues with the country name of North Macedonia & Eswatini
> Update country-util to the latest version

- components/footer.js
This PR contains fixes to issues identified in the footer. Related to issue #9
> Fix footer issues

- components/country/overview-charts.js
Fixes: https://github.com/ooni/explorer/issues/103
> Round the axis labels

- components/landing/highlight-box.js
- components/landing/highlights.json
- pages/index.js
This PR includes edits to the Highlights page to include search links that pertain to the specific findings mentioned in the reports/highlights.
This PR also addresses the following 3 tickets:
https://github.com/ooni/explorer/issues/109
https://github.com/ooni/explorer/issues/108
https://github.com/ooni/explorer/issues/126
> Edited copy & search links on Highlights page

- components/measurement/nettests/web_connectivity.js
> Fix bug in extracting test time stamp to render web_connectivity details

- pages/index.js
> Landing page button

- components/country/websites-charts.js
> Remove references to categories from country page websites section

- components/measurement/CommonDetails.js
Closes: https://github.com/ooni/explorer/issues/155
> Fix issue with rendering the engine version

- components/measurement/CommonSummary.js
> Show flag in measurement page hero next to country name

- components/measurement/CommonDetails.js
- pages/search.js
> Remove 'Load More' button when all available results are displayed

- components/landing/highlight-box.js
> Add hover and click effects to  buttons on landing page hightlights

- components/country/url-chart.js
> Truncate long URLs in Website section on country page

- pages/countries.js
> Fix spacing around country cards on country list

- components/measurement/DetailsBox.js
> Use expand/collapse icon from MD for collapsible boxes

- components/country/overview.js
> Comment out 'In a Nutshell' section on country page

- components/measurement/nettests/web_connectivity.js
> Fix empty http data

- components/measurement/Hero.js
> Fix alignment issue in Hero due to extra Flex component

- next.config.js
> Fix publicPath to access css fonts

- components/country/apps-stats-circumvention-row.js
> Vanilla Tor stats on country page

- pages/countries.js
Closes #220 (Typo "Measurments")
Also added improvements to layout on mobile screens.
**Before**
**After**
> Countries Page Fixes

- components/search/filter-sidebar.js
- package.json
- yarn.lock
Closes #52 
Closes #83 
Closes #138
> Contextual search filters

- pages/countries.js
> Replace Antarctica with Oceania

- components/measurement/Hero.js
- components/measurement/nettests/mlab_servers.json
- components/measurement/nettests/mlab_utils.js
- components/measurement/nettests/ndt.js
> Show NDT server location

- components/country/overview-charts.js
> Fix overview charts upon toggling test groups

- components/measurement/nettests/whatsapp.js
> Check for valid tcp_connect key in whatsapp msmt

- components/measurement/CommonDetails.js
> Show raw measurement box open by default

- components/country/asn-selector.js
- components/country/websites-charts.js
- components/country/websites.js
- components/measurement/CommonDetails.js
> Make ASN Selector a controlled component

- components/measurement/nettests/facebook_messenger.js
Fixes: https://github.com/ooni/explorer/issues/241
> Fix issue with missing tcpConnect results

- components/search/filter-sidebar.js
- pages/search.js
> Show and use current date in default search page

- components/search/results-list.js
> Show consistent url in search result

- components/search/results-list.js
> Hide indicators in search results

- components/country/apps-stats-chart.js
- components/country/url-chart.js
> Country charts polish

- components/search/filter-sidebar.js
Closes #12 
Validates `ASN` and `Input` fields. Shows error message below the field.
> Add input validations

- components/country/apps-stats-circumvention-row.js
- components/country/apps-stats.js
- components/country/network-properties.js
- components/country/overview-charts.js
- components/country/overview.js
- components/country/websites-charts.js
- components/country/websites.js
> Add zero state for missing data

- components/search/filter-sidebar.js
> Fix bug when hiding input filter in search

- components/country/overview-charts.js
> Use proper names of test groups in chart tooltips

- components/search/filter-sidebar.js
> Rearrange fields in search filter

- components/country/websites-charts.js
- components/country/websites.js
> Fix indefinite loading

- pages/search.js
Shows an error message with details when search query times out.
Closes #321
> Improve error reporting on failed searches

- components/country/apps-stats.js
> Remove unnecessary code

- pages/index.js
> Passes href for link in landing page

- package.json
- pages/_app.js
- yarn.lock
Fixes #326 
This just adds basic page visit analytics. Once we start seeing data, we can consider adding events to understand more specific interactions that are of interest to our UX studies.
> Add code for analytics with matomo

- pages/measurement.js
> Use country-util instead of API call for country name

- components/search/FilterSidebar.js
> Allow selecting tomorrows date in search filter

- components/vendor/SpinLoader.js
This fixes: https://github.com/ooni/explorer/issues/407
> Update the spinloader to work with styled-components v4

- components/Footer.js
> Use blue9 from theme for footer background

- components/measurement/nettests/WebConnectivity.js
> Handle when web connectivity requests data is missing from test_keys

- .github/workflows/main.yml
- .travis.yml
- components/search/ResultsList.js
- cypress.json
- cypress/integration/countries.e2e.js
- cypress/integration/country.e2e.js
- cypress/integration/home.e2e.js
- cypress/integration/measurement.e2e.js
- cypress/integration/search.e2e.js
- cypress/plugins/index.js
- cypress/screenshots/README
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- yarn.lock
> End to end testing with Cypress

- components/measurement/DetailsBox.js
This Pull request solves #428 
Changes:
* Solves the overflow of JSON Data in mobile screen
> JSON View Data overflows in search small screen

- cypress/integration/country.e2e.js
- pages/country.js
This pull request fixes #164 
It handles case senstivity in URLs where /country/al can be treated as /country/AL and updates the URL shown in the browser.
> Case sensitivity of country codes

- components/search/FilterSidebar.js
- cypress/integration/search.e2e.js
- pages/country.js
> Fix meta tag typo

- components/search/FilterSidebar.js
- cypress/integration/search.e2e.js
- package.json
- pages/country.js
Fixes #464
Network count was being shown instead of measurement count in the country page meta tag
> Release 2.0.9

- components/DatePicker.js
- components/measurement/Hero.js
- components/search/FilterSidebar.js
- cypress/integration/measurement.e2e.js
- cypress/integration/search.e2e.js
- cypress/support/commands.js
- package.json
- pages/search.js
- yarn.lock
> More e2e testing

- index.js
- next.config.js
- package.json
> Switch to using the hostname api.ooni.io

- package.json
- pages/nivo-toy.js
- yarn.lock
This adds https://codesandbox.io/s/pbgg4 to OONI Explorer
> Add nivo-toy to OONI Explorer

- .github/workflows/main.yml
> Bump version of github actions to v2

- components/landing/Stats.js
- package.json
> Show monthly coverage stats skipping last month data

- package.json
- yarn.lock
Trivial change. Merging directly.﻿
> Pin dependencies in yarn.lock for security fixes

- components/country/CountryHead.js
- components/measurement/HeadMetadata.js
- components/measurement/nettests/Dash.js
- components/measurement/nettests/FacebookMessenger.js
- components/measurement/nettests/HTTPHeaderFieldManipulation.js
- components/measurement/nettests/HTTPInvalidRequestLine.js
- components/measurement/nettests/Ndt.js
- components/measurement/nettests/Psiphon.js
- components/measurement/nettests/Telegram.js
- components/measurement/nettests/Tor.js
- components/measurement/nettests/VanillaTor.js
- components/measurement/nettests/WebConnectivity.js
- components/measurement/nettests/WhatsApp.js
- components/test-info.js
- cypress/integration/measurement.e2e.js
- pages/country.js
- pages/measurement.js
- Measurement pages metadata being handled with HeadMetadata
- Country pages metadata being handled with CountryHead(instead of IntlHead)
> Custom metadata for measurement pages

- package.json
- pages/country.js
> Hide networks section on country page

- pages/_app.js
- pages/_error.js
- pages/index.js
- pages/measurement.js
Show the error message causing the page to crash.
> Handle missing raw_measurement

- components/country/URLChart.js
- components/measurement/nettests/WhatsApp.js
- pages/experimental/mat.js
* Removes the disclaimers on whatsapp pages
* Fixes experimental website-centric page
> Usability improvements

- components/CollapseTrigger.js
- components/Footer.js
- components/country/AppsStatsCircumventionRow.js
- components/country/AppsStatsRow.js
- components/measurement/AccessPointStatus.js
- components/measurement/DetailsBox.js
- package.json
- yarn.lock
In this PR, I have addressed issue #487. For this, I have done the following:
I didn't replace simple props with transient props in [Overview.js](https://github.com/ooni/explorer/blob/master/components/country/Overview.js) file because the styled component `NwInterferenceStatus` was commented out later in the file.
I opened this PR earlier but later closed it because I accidentally committed to my master branch of the `explorer`. Now I have changed my branch, made the changes, and opened it again. :)
@sarathms kindly take a look
> FIX: DOM Warnings By Using Transient Props

- components/FeedbackFloat.js
> Fix Feedback Float button alignment

- components/search/ResultsList.js
Fixes: https://github.com/ooni/explorer/issues/438
> Add support for displaying the anomaly type in the search listing

- .env
- .env.production
- .env.test
- .gitignore
- Dockerfile
- components/aggregation/website/Debug.js
- components/aggregation/website/WebsiteInCountry.js
- components/country/AppsStats.js
- components/country/AppsStatsChart.js
- components/country/AppsStatsCircumvention.js
- components/country/NetworkProperties.js
- components/country/URLChart.js
- components/country/Websites.js
- components/country/WebsitesCharts.js
- components/landing/Stats.js
- components/measurement/CommonDetails.js
- components/measurement/MeasurementNotFound.js
- index.js
- next.config.js
- package.json
- pages/countries.js
- pages/country.js
- pages/experimental/mat.js
- pages/experimental/website/index.js
- pages/index.js
- pages/measurement.js
- pages/search.js
Fixes #492 
Uses [environmental variables](https://nextjs.org/docs/basic-features/environment-variables) feature of Next.js
> Move environment variable definitions to .env files

- components/search/FilterSidebar.js
- package.json
- yarn.lock
Also fixes the open security alert by upgrading nextjs to `10.2.x`
> Enable anomaly search for whatsapp tests

- components/Footer.js
- components/search/FilterSidebar.js
- utils/sentry.js
* Fix feedback button
* Enable anomaly search for Signal tests
* Add link to github repo in footer
> Misc fixes

- components/search/FilterSidebar.js
Closes: https://github.com/ooni/explorer/issues/633
> Fix crash when manually changing the date filter in search page

- components/aggregation/mat/FunnelChart.js
- components/aggregation/mat/StackedBarChart.js
- components/aggregation/mat/TableView.js
- pages/experimental/mat.js
Fixes issue introduced in 0a396aa
> Fix how ok_count is calculated

- components/NavBar.js
- components/aggregation/mat/ChartHeader.js
- components/aggregation/mat/GridChart.js
- components/aggregation/mat/MATContext.js
- components/aggregation/mat/RowChart.js
- components/aggregation/mat/TableView.js
- components/aggregation/mat/labels.js
- components/dashboard/Charts.js
- pages/experimental/mat.js
> Circumvention charts polish

- .env
This fixes: https://github.com/ooni/explorer/issues/695
> Set some sane values for the default env

- components/aggregation/mat/Form.js
Fixes the responsive UI of the form on every device.
Previous State of the form on mobile screen -
New State of the form on mobile screen -
Signed-off-by: GermaVinsmoke <vaibhav1180@gmail.com>
> MAT responsive form UI

- cypress/integration/mat.e2e.js
- next.config.js
- pages/chart/mat.js
- Move MAT to /chart/mat
- Add basic E2E test to check if MAT loads
> MAT URL changes

- cypress/integration/search.e2e.js
Changed line 3 of cypress/integration/search.e2e.js
> Fixed a typo in search.e2e.js

- pages/chart/mat.js
> Show link to aggregation API query

- components/Footer.js
- public/static/lang/en.json
Version number has been fixed since the issue was open.
Closes https://github.com/ooni/explorer/issues/629
> Fix copyright year

- components/search/FilterSidebar.js
Closes https://github.com/ooni/explorer/issues/605
> Allow tld to be of any length

- components/network/Form.js
I forgot to update the network page form while simultaneously merging https://github.com/ooni/explorer/pull/750 and https://github.com/ooni/explorer/pull/711
I replaced the components/libraries that don't exist in the project anymore in order to fix the build
> Fix form on network page (replace with new dateRange component)

- components/measurement/StatusInfo.js
- components/measurement/nettests/FacebookMessenger.js
- components/measurement/nettests/Telegram.js
- components/measurement/nettests/WebConnectivity.js
- components/measurement/nettests/WhatsApp.js
- public/static/lang/en.json
Closes https://github.com/ooni/explorer/issues/545
> Refactor messaging measurement pages to look more consistent

- pages/measurement/[[...report_id]].js
Also closes https://github.com/ooni/explorer/issues/701
> Fix parsing error when there is no raw_measurement

- components/measurement/nettests/WebConnectivity.js
- public/static/lang/en.json
Closes https://github.com/ooni/explorer/issues/783
> Remove external links from measurement page

- .github/ISSUE_TEMPLATE.md
The correct spelling is "accordingly"
> Minor Typo corrected in issue template

- pages/search.js
Closes https://github.com/ooni/explorer/issues/413
> Search page refactoring

- components/test-info.js
Closes https://github.com/ooni/explorer/issues/814
> Move vanilla tor from legacy to experimental category

- components/dashboard/Form.js
- components/network/Form.js
- pages/chart/circumvention.js
- pages/chart/mat.js
- pages/network/[asn].js
Closes https://github.com/ooni/explorer/issues/797
> Fix back button where params applied programmatically

- pages/search.js
Fixes #833 
Signed-off-by: GermaVinsmoke <vaibhav1180@gmail.com>
> Search page filter values

- components/network/Calendar.js
Closes https://github.com/ooni/explorer/issues/771
> Update coverage chart color scale and add a legend

- components/NavBar.js
Closes https://github.com/ooni/explorer/issues/896
> Add mobile menu

- components/aggregation/mat/CustomTooltip.js
If time grain isn't "day", use ( start + time grain ) as until
Resolves #864
> CustomTooltip: change link to measurements

- components/DateRangePicker.js
- components/aggregation/mat/Form.js
- components/search/FilterSidebar.js
- package.json
- yarn.lock
> Improve form performance on MAT and search pages

- components/NavBar.js
Fixes https://github.com/ooni/explorer/issues/931
> Fix language select styling

- components/NavBar.js
Adds data attributes to NavBar items so we can track click events on them.
https://umami.is/docs/track-events
Closes https://github.com/ooni/explorer/issues/937
> Add event tracking to NavBar

- .env.development
- .env.test
- cypress.config.js
- cypress/mocks/handlers.js
Replace https://ams-pg-test.ooni.org with https://backend-hel.ooni.org
> Update env vars

- pages/findings/dashboard.js
- utils/index.js
Closes https://github.com/ooni/explorer/issues/956
> Set findings start and end time to UTC timezone

- components/country/Calendar.js
- package.json
- yarn.lock
Fixes https://github.com/ooni/explorer/issues/986
> Fix calendar components on country pages

- next.config.js
https://github.com/ooni/ooni.org/issues/1660
> Exclude Explorer previews from indexing

- components/Chart.js
- components/ThirdPartyDataChart.js
- components/country/CountryDetails.js
- package.json
- pages/as/[probe_asn].js
- yarn.lock
Closes https://github.com/ooni/explorer/issues/991
> Use react-intersection-observer to load charts only when in viewport

- middleware.js
Related to https://github.com/ooni/explorer/issues/996
> Add minimal language detection for embeddable measurement pages

- .github/workflows/vrt.yml
- .gitignore
- components/country/Calendar.js
- components/login/LoginForm.js
- components/measurement/FeedbackBox.js
- components/vendor/SpinLoader.js
- lostpixel.config.ts
- package.json
- pages/as/[probe_asn].js
- yarn.lock
Closes https://github.com/ooni/explorer/issues/1008
> Add lost-pixel for visual regression testing

- components/NavBar.js
Closes https://github.com/ooni/explorer/issues/1021
> Add caret icon to language selector dropdown

- components/measurement/nettests/Tor.js
Closes https://github.com/ooni/explorer/issues/420
> Update Tor component table styling

- components/aggregation/mat/GridChart.js
- components/aggregation/mat/RowChart.js
Closes https://github.com/ooni/explorer/issues/1031
> Fix table chart height when there are 9 items selected
