ooni/explorer

components/layout.js
next.config.js
package.json
pages/_document.js
scripts/now-preview.sh
yarn.lock

This adds the Fira Sans typeface via a webpack loader and injects a global stylesheet using postcss.
I haven't figured out why it's not working in the development environment, though I don't see this as a major issue as we use the stylesheet only for fonts.

Add support for embedding the fira sans typeface

---

components/colors.js
components/country/overview-charts.js
components/country/tooltip.js
components/country/url-chart.js
components/search/results-list.js

Implements tooltips as per the discussion in #84.
I also cleaned up a bit the chart in the overview section, but I could not figure out a way to make the two charts be linked (i.e. so that when you scrub over any of the two graphs the tooltip appears on both of them).

Get the URL charts to look decent

---

components/nav-bar.js
components/search/results-list.js
index.js

This fixes problems with handling the URLs schema used by the old explorer e.g `https://explorer.ooni.torproject.org/measurement/report-id?input=website-url-tested`
The query string was being omitted when handing off the request to the new URL format. It is not captured and sent to the request handler.

Handle legacy explorer urls

---

components/country/apps.js
components/country/overview.js
components/country/websites.js
components/formatted-markdown.js
components/measurement/SummaryText.js
package.json
pages/index.js
yarn.lock

Use the above component to parse markdown in these places:

Parse markdown in translated strings

---

components/search/results-list.js

This is a hotfix to not show all measurements as failure, while we work on solving it on the pipeline via: https://github.com/ooni/pipeline/issues/112

Implement hotfix for measurement failures

---

components/nav-bar.js

`next/link` doesn't pass the href prop automatically for children other than `<a>`

Make logo visually clickable

---

components/measurement/nettests/web_connectivity.js

This was added to demonstrate how longer strings in header values are handled. Was committed accidentally.

Remove repeated headers from HTTP responses

---

components/measurement/Hero.js

Set bigger font size for subtext under measurement status label

---

components/flag.js
components/measurement/CommonSummary.js

Closes #116 
As per https://github.com/ooni/explorer/issues/116#issuecomment-499896501, we now have a white border around the flag.
Awaiting response from @hellais on above issue thread for another possible commit in this PR.

Flag and country name in Measurement page

---

components/country/overview-charts.js

By doing it manually we are able to ensure that the values we tick to
are always whole numbers and are always 4.
This fixes: https://github.com/ooni/explorer/issues/204

Manually compute the tickValues based on the maxima.

---

components/measurement/CommonDetails.js
components/measurement/DetailsBox.js

Toggle sections by clicking header

---

components/measurement/CommonDetails.js

Fix the layout mess in the common details at the bottom of measurement pages.

Fix layout of common details on measurement pages

---

components/measurement/nettests/dash.js

Fixes crashing measurement pages like [this](http://explorer-beta.ooni.io/measurement/20190728T224449Z_AS327712_sJlefoZrC8Lhq9OUyVV40mOCzWJWQn0Iq5PHW9bQtJ3AUjvQWF)

Render error page when missing keys in DASH test

---

components/measurement/Hero.js
components/measurement/nettests/web_connectivity.js

Closes #179 
Now we show reason in Hero like so:
Works on confirmed blocked pages too:
I found an exception in this measurement. It is flagged with `isConfirmed = true` because it does serve a block page. But it shows up [normal on old explorer](https://explorer.ooni.io/measurement/20190703T163625Z_AS8708_UwLHVRiAoYGcScetNQ2uobFjyawbW11oqw4ZMIN8qJEZEF41pX?input=http:%2F%2Fwww.slotland.com). Because `test_keys.blocking = false`, it doesn't pick up from the map of reasons we use otherwise. Is there a way to determine reasons for such measurements? Just apply `blockingReason.http-diff` to all confirmed ones?
https://explorer-beta.ooni.io/measurement/20190703T163625Z_AS8708_UwLHVRiAoYGcScetNQ2uobFjyawbW11oqw4ZMIN8qJEZEF41pX?input=http://www.slotland.com

Show anomaly or blocking reason in hero

---

components/search/filter-sidebar.js

Closes #321 
So far, this fixes the formatting bug when the input field is manually edited to any value. While it prevents arbitrary values from being inserted into the search query, it still accepts bizarre values like `1111` which are valid date formats (not ISO).

Fix for manual date entry

---

components/country/apps-stats-circumvention-row.js
package.json
yarn.lock

Upgrades `ooni-components` to use the right icon like in the screenshot.

Use correct icon for Vanilla Tor in circumvention section

---

components/test-info.js

Change color name from `fuschia` to `fuchsia`
Fixes #18

Use corrected name for color fuschia

---

components/header.js
pages/country.js

This provides RSS feeds to subscribe to events detected by 'fastpath' (a component in the pipeline). The following different feeds will be made available:
Fixes #330

Add links to RSS feeds from Fastpath event detector

---

CHANGELOG.md
package.json
yarn.lock

- Added this changelog
- Added 'UTC' label to measurement timestamps (#328)
- Added explorer version in footer (#329)
- Added link to fastpath event detector feed (#342)
- Refactored all file names exporting components to PascalCase format (#336)
- Multiple dependency upgrades via dependabot
- Use the correct icon for Vanilla Tor section on country page (#327)
- Replace deprecated `fuschia` color with `fuchsia` (#337)
- Fix minor bug by removing unused code (#340)

Release 2.0.4

---

pages/search.js

To update the URL as we update search filters, we were using `Router.push` that triggered navigation, which in turn called `getInitialProps` and the API requests right after they were already initiated in `onApplyChange`.
The solution according to this [spectrum-chat](https://spectrum.chat/next-js/general/change-url-without-triggering-navigation~12ba234c-ad05-4783-8342-8a4a07661a9c) is to perform a shallow ~rendering~ routing which updates the URL without navigation.
Fixes #350

Fix multiple API requests on search page

---

components/measurement/nettests/WebConnectivity.js

Fixes #358 
Adds a check for queries to exist and not be `undefined`. I have not shown any kind of message for No Queries. Not sure if that's needed.

Adds check for queries array in DNS Queries section

---

components/country/AppsStatsRow.js
components/country/URLChart.js
components/search/FilterSidebar.js
pages/search.js

Fixes #361 
I have changed the `today` value everywhere to add 1 day so that the filter includes today's measurements. In doing so, I have changed the name of the variable from `today` to `until` which is something I saw used in the API repository. `today` sounded like a bad variable name, since clearly it's `tomorrow`. I am up to changing the variable name from `until` to something like `tomorrow` or `untilToday` if you all feel that's more suitable/relevant.

Fixes the until today logic to include measurements today

---

CHANGELOG.md
package.json

- Added regex to allow search by IP address in the domain field (#367)
- Added matomo based analytics (#369)
- Fixed bug where duplicate API requests were made for search queries (#353)
- Fixed bug in rendering DNS queries on WebConnectivity measurement pages (#363)
- Fixed 'until today' logic in search to include today's measurement (#364)

Release v2.0.5

---

components/measurement/nettests/WebConnectivity.js

To work around the misalignment of anomaly detection logic between fastpath, pipeline and explorer
Currently, fastpath detects anomalies with a logic different from that of legacy pipeline. Resulting in measurements being flagged as anomalies in the search result, although the values in `test_keys` do not point to an anomaly.
This fix works around that problem by using the values in `test_keys` to determine if the measurement is an anomaly or not.
Fixes #374

Ignore anomaly flag from fastpath

---

CHANGELOG.md
package.json

- Fixed bug in rendering measurements with misaligned anomaly flag (#374)
- Fixed error message copy for search page failures (#370)

Release v2.0.6

---

components/search/ResultsList.js

Fixes #292 
We now skip formatting the `input` value like in the case of `web_connectivity` since they are all domains unlike URLs with path. Also vertically aligns the last two columns with the rest of the row.

Fix seach results for DNS Consistency tests

---

components/measurement/nettests/WebConnectivity.js

Here is an example measurement which triggers this error: https://explorer.ooni.org/measurement/20170605T124503Z_AS0_eVo3z6wXAYDVrAZDsgqiM7pPlLuKR7l4zNF8oEUrGmZ62HWU4l?input=http:%2F%2Frockettube.com

Make the blockingReason key fetch more robust

---

components/measurement/SummaryText.js
components/measurement/nettests/WebConnectivity.js
pages/measurement.js

This PR contains proposed fixes to the issues discussed recently.
* Restructuring the code in `WebConnectivity.js` measurement page component
* Injecting the message from `scores.msg` for WhatsApp measurement pages

Fix inconsistent msmt pages

---

components/measurement/nettests/Telegram.js
components/measurement/nettests/WebConnectivity.js

Fixes #381 
Addresses the issue in Telegram and WebConnectivity pages. Other places where this key is used are covered already:
[FacebookMessenger.js](https://github.com/ooni/explorer/blob/master/components/measurement/nettests/FacebookMessenger.js#L75)
[WhatsApp.js](https://github.com/ooni/explorer/blob/master/components/measurement/nettests/WhatsApp.js#L89)
Are there other keys from the spec that could go missing? Or is this only specific to `miniooni` generated measurements?

Handle cases where test_keys.tcp_connect is missing

---

components/country/OverviewCharts.js

This pull request fixes #458 
The overview charts in the country page are rendered .

overview charts are rendered in country page

---

components/Header.js
components/country/IntlHead.js
pages/country.js

Helps with #202 
- Changed the og:description to show a summary of the measurements about the country
- Changed the og:title to show the appropriate title with current country's name in it
Possible improvements: use Intl strings instead of plain english

Improved meta in country pages

---

components/measurement/PerformanceDetails.js
components/measurement/nettests/Ndt.js
components/measurement/nettests/mlab_utils.js

#452 
Changes done for Ndt7 measurements
The Ndt4/5 measurements still look the same.
I tried to have as little replication of code as i could without making the code a mess to read.

Implemented measurement page for Ndt7

---

components/measurement/DetailsHeader.js

Add links to test descriptions on measurement pages

---

components/NavBar.js
pages/countries.js

Fixes #446 
This pull request adds the responsiveness in mobile -view
1. Desktop-view
2. Mobile-view

fixed responsiveness in header on the countries page

---

components/country/AppsStatsRow.js
components/country/URLChart.js
components/measurement/DetailsHeader.js

The `<Link>` component in ooni/design-system currently fails
to apply the default color for the link correctly. These changes
do this manually until the bug is fixed.

Use blue7 for links

---

components/Footer.js

Eliminates annoying errors in the browser console in dev environment.
Earlier `next/link` would work fine even if the target `href` is an external URL. Now it doesn't.
Related to: https://github.com/vercel/next.js/blob/master/errors/invalid-href-passed.md

Dont use next/link for footer links which are external

---

components/measurement/MeasurementContainer.js
components/measurement/PerformanceDetails.js
components/measurement/nettests/Dash.js
components/measurement/nettests/HTTPHeaderFieldManipulation.js
components/measurement/nettests/Ndt.js
components/measurement/nettests/WebConnectivity.js
components/measurement/useTestKeyController.js

Fixes #416 
Makes sure all measurement pages render without crashing when any of the keys  in `test_keys`are not found in the measurement.
Also includes a development toolbar (not added to any pages) that allows us to control the values inside different `test_keys`

Handle missing test keys

---

components/SocialButtons.js
components/country/PageNavMenu.js
components/measurement/DetailsHeader.js
pages/country.js
pages/measurement.js

Things to be discussed:
- Design changes?
- We can include a default text with the link on twitter. Should we include something like: "Check out this measurement on OONI Explorer: {link goes here}" ?

Sharing buttons on both Country and Measurement pages

---

components/measurement/CommonSummary.js
components/measurement/DetailsHeader.js
components/measurement/MeasurementContainer.js
components/measurement/MeasurementNotFound.js
components/measurement/nettests/Default.js
cypress/integration/measurement.e2e.js
index.js
next.config.js
package.json
pages/measurement.js
static/mock-measurement.json

Fixes #489
Uses the new `/api/v1/measurement_meta` API to fetch measurement data.

Refactored measurement page using refactored API

---

components/measurement/MeasurementContainer.js

Superseding https://github.com/ooni/explorer/pull/501
Related to #495 
- Consider `AS0` and `0` as invalid inputs for the `probe_asn` field in search queries
- Omit search result items with `probe_asn: "AS0"` in them
- Do not generate pages for measurements which have `AS0` in the report id (part of the URL)
- Bump version to `2.0.10`

Make it harder to find AS0 measurements (+merge fix into master)

---

components/measurement/nettests/WebConnectivity.js

Fixes #500 
Now we show ipv4 for `A` type, `ipv6` for `AAAA` and `hostname` for `CNAME` and ignore everything else.

Handle AAAA answers in DNS queries

---

CHANGELOG.md
package.json
pages/search.js

Fixes #507 
* Going directly to `/search` sets the since date to `${today} - 30`
* If there is already an `until` date in the page URL, since date is set to `${until} - 30`

Set default since date in search to 30 days from until date

---

components/search/ResultsList.js
pages/search.js

Fixes #425 
Enables indicators on IM tests. To filter out measurements coming from batch pipeline, the condition used is to check if `scores` key has object with at least one property. This goes with the assumption that fastpath measurements have non-zero properties in `scores` object.
Should we be extending this to the circumvention test too?

Show search results indicators

---

components/measurement/nettests/FacebookMessenger.js
components/measurement/nettests/Telegram.js
components/measurement/nettests/WebConnectivity.js
components/measurement/nettests/WhatsApp.js
cypress/integration/measurement.e2e.js

This fixes the problem in pages like https://explorer.ooni.org/measurement/20210128T090057Z_webconnectivity_IT_30722_n1_WOS6jGJBP1UMopM9?input=http%3A%2F%2Fvoice.yahoo.jajah.com%2F where test_keys has null values in `tcp_connect`, `queries.[].answers` ﻿
We explicitly check that the value exists and is an `Array`

Handle missing array values in test_keys

---

components/Footer.js

Before
After
The footer was previously way too small, this PR bumps it up to a more reasonable font size.

Bump up the font-size of the footer

---

components/aggregation/mat/Charts.js

This PR rotates the date labels by 45 degrees so they become more legible and moves the y axis label outside of the number area to improve legibility.

Improve the labels of the mat

---

components/measurement/SummaryText.js

As stated in issue #541, it only showed the date on IM test pages
`On March 17, 2021, WhatsApp was reachable on AS7922 in United States`
However in the web_connectivity pages it said
`On March 02, 2020, 9:17 PM UTC, http://prachatai.com was accessible when tested on AS15751 in Ireland.`
It will now show Date and Time in both pages, adding to consistency.
@sarathms I have removed the `<abbr>` and the commented line as you had pointed out in #558 
As for the momentJS dependency, I am looking into possible alternatives. I will open another PR with my attempt at replacing the dependency.
I have closed #558 because the push was on master.
Kindly review :)

[ENHANCEMENT] Inconsistent date-time in measurement page summary text

---

components/search/FilterSidebar.js
components/search/Radio.js
components/search/ResultsList.js
cypress/integration/search.e2e.js

Fixes #581
Additionally,
﻿- Show only relevant status filter for tests (e.g no 'Confirmed' for 'telegram')
- Show anomaly status for middlebox tests in search results. Not directly related, but bundling this change in here.

Hide status filter when irrelevant for selected test

---

components/colors.js
components/search/ResultsList.js

This was previously disabled because of a backend bug that
marked all measurements as errors. We now have more accurate flags
to show failed measurements in the search results.
﻿

Show failed measurements in search results

---

components/search/FilterSidebar.js
package.json
yarn.lock

Hot fix for bug that crashed search page because it couldn't find the module '@hookform/devtools'

Fix dependency on react-hook-form devtools

---

cypress/integration/search.e2e.js
package.json
yarn.lock

Cypress started failing after Nextjs was upgraded during which
we switched from `.babelrc` to `babel.config.js`. It seems this
version of Cypress didn't like it. The easier fix was to
make one of options `runtime` explicit in the new file.
This also fixes a problem with one integration test failing randomly.
It was happening when the test starts before a page navigation from a
previous test completes. Moved it to top to avoid that. `cy.go()` is
supposed to wait for the navigation. But again, maybe it is the cypress version.

Fix cypress config and search page tests

---

components/aggregation/mat/ChartHeader.js
components/aggregation/mat/GridChart.js
components/aggregation/mat/MATContext.js
components/aggregation/mat/StackedBarChart.js
components/aggregation/mat/TableView.js

* Uses a single component to show the header on the 1-axis chart, 2-axis chart and the PT dashboard charts.
* Also fixes the issue of the header title not updating when country selection is changed back to 'All Countries'.

Generate ChartHeader based on MATContext

---

.env.production
components/aggregation/mat/CustomBarItem.js
components/aggregation/mat/GridChart.js
components/aggregation/mat/MATContext.js
components/aggregation/mat/RowChart.js
components/aggregation/mat/TableView.js
components/aggregation/mat/VirtualRows.js
components/dashboard/Charts.js
pages/chart/circumvention.js

This addresses the issue discussed in https://github.com/ooni/explorer/pull/653#issuecomment-1054295488
> When you click on the tooltip for one of the last charts it's displayed hidden below the overflow container. Can we either make the tooltip go out of the container or if we can't do that, make it render above the click instead of below?
> ![Screenshot 2022-02-28 at 15 02 47](https://user-images.githubusercontent.com/424620/155996617-54d81bc3-9198-4531-b115-6b887dbdada0.png)
This is solved by not using virtual lists to render the rows when the counts are low. Currently the threshold is set to `10` rows. 
When virtualized for longer lists, the scroll action is more natural to make such tooltips visible. However, in most case, the tooltip is anchored in a way that it is visible.

Tooltip visibility in Circumvention charts

---

components/aggregation/mat/Form.js
components/aggregation/website/Form.js
components/country/AppsStatsCircumventionRow.js
components/country/AppsStatsRow.js
components/country/URLChart.js
components/dashboard/Form.js
components/landing/Stats.js
components/measurement/CommonSummary.js
components/measurement/HeadMetadata.js
components/measurement/SummaryText.js
components/measurement/nettests/WebConnectivity.js
components/search/FilterSidebar.js
components/search/ResultsList.js
cypress/integration/measurement.e2e.js
cypress/integration/search.e2e.js
package.json
pages/experimental/website/index.js
pages/measurement/[[...report_id]].js
pages/search.js
services/dayjs.js
yarn.lock

Related issue: https://github.com/ooni/explorer/issues/510
Also fixes an issue with inconsistent time display - described in: https://github.com/ooni/explorer/issues/515
Initially, I intended to go with date-fns, but unfortunately it doesn't have a nice interface to work with timezones/utc and it required working a lot with the native Date object, which defeats the purpose of a library altogether. After a bit of exploration and testing, I decided to go with day.js, which is very lightweight, just as popular, and with a very similar interface as momentjs - which makes it also easy to replace.
Unfortunately, it's not possible to get rid of moment.js completely just yet since the `Datetime` component depends on it. I will follow up with [this …

Replace momentjs with dayjs where possible

---

components/aggregation/mat/Form.js
pages/chart/mat.js

This sets the default chart shown on `/chart/mat` to "country-wise daily-counts for `twitter.com` in last 30 days"

Show country-wise data for twitter.com when MAT opens from NavBar

---

components/Flag.js

Current case -
https://user-images.githubusercontent.com/32815509/158387128-9fb7ad14-77bd-4ff9-b065-07e58a53075d.mp4
It is loading every country image at the time of page load, I think creating too much pressure on the main javascript thread. How about showing images only after we scroll?
New lazy loading case - 
https://user-images.githubusercontent.com/32815509/158387324-f6350bbf-1293-4d51-8c62-163906edc37e.mp4

lazy loading the country images

---

pages/_error.js
pages/measurement/[[...report_id]].js

Closes https://github.com/ooni/explorer/issues/776
Can be merged **after** https://github.com/ooni/explorer/pull/770

Fix error handling for measument page when endpoint returns error

---

components/search/ResultsList.js

This is related to the issue that was reported on Slack where search with &failure=true fails due to localization id not being defined inside `messages`, even though it is present in the translation file:
https://explorer.ooni.org/search?since=2022-07-06&until=2022-08-06&failure=true&probe_cc=IR&test_name=tor

Refactor ResultsList so that localization ids are defined in one place

---

pages/measurement/[[...report_id]].js

Adds stricter report_id regex to avoid making unnecessary api requests.
Regex matches the one on the backend: https://github.com/ooni/api/pull/301

Stricter report_id validation

---

components/aggregation/mat/ChartHeader.js

Current version of legend looks like this on mobile which is not responsive at all. The legends are overlapping on each other.
Changed it to this version 
Signed-off-by: GermaVinsmoke <vaibhav1180@gmail.com>

chart header responsive legend

---

components/measurement/nettests/WebConnectivity.js

We add a new column to the table of DNS Answers.  This is currently used to present ASN and (ISP) organization name where present.  In order to improve readability, some columns (TTL, type, class) where made narrower.
Fixes #821

DNS Answers: Add ancillary information

---

components/measurement/nettests/VanillaTor.js

Fix checks for vanilla_tor to remove parsing of test_keys

Use only backend provided values for vanilla_tor

---

components/landing/Stats.js

fix(Stats.js): display correct monthly measurements after changing language

---

components/country/CountryDetails.js
pages/_error.js
pages/country/[countryCode].js

Closes https://github.com/ooni/explorer/issues/913
We should eventually revisit country page validations and make them even stricter - limit the country codes only to the ones actually existing.

Add more validation for country pages, fix error handling, decouple components

---

components/aggregation/mat/Form.js
components/search/FilterSidebar.js
pages/search.js
public/static/lang/en.json

closes https://github.com/ooni/explorer/issues/867

Add support for ooni run id filtering on measurements search page and mat
